Save current progress
The script is almost there, I keep getting bugs. I am presently
experiencing:

```
  File "/data4/sirothia/proxima_btry/msdir/DynSpecMS/ClassDynSpecMS.py", line 939, in StackAll
    self.processJob(iJob)
  File "/data4/sirothia/proxima_btry/msdir/DynSpecMS/ClassDynSpecMS.py", line 987, in processJob
    self.delShm(iJob)
  File "/data4/sirothia/proxima_btry/msdir/DynSpecMS/ClassDynSpecMS.py", line 990, in delShm
    shared_dict.SharedDict.delete_item("DATA_%i"%(iJob))
TypeError: delete_item() missing 1 required positional argument: 'item'
```